# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pkg/enginerpc/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1apkg/enginerpc/common.proto\x12\rpkg.enginerpc\"Q\n\x0cSyncFileInfo\x12\x16\n\x0e\x66rom_file_name\x18\x01 \x01(\t\x12\x14\n\x0cto_file_name\x18\x02 \x01(\t\x12\x13\n\x0b\x61\x63tual_size\x18\x03 \x01(\x03\x42\x36Z4github.com/longhorn/longhorn-interface/pkg/enginerpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.enginerpc.common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z4github.com/longhorn/longhorn-interface/pkg/enginerpc'
  _globals['_SYNCFILEINFO']._serialized_start=45
  _globals['_SYNCFILEINFO']._serialized_end=126
# @@protoc_insertion_point(module_scope)
